services:
  db:
    container_name: afapa-db
    image: mongo:8.0-noble
    restart: unless-stopped
    ports:
      - 27017
    volumes:
      - db_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-afapa}
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --username \"$MONGO_INITDB_ROOT_USERNAME\" --password \"$MONGO_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin --quiet --eval \"db.adminCommand({ ping: 1 })\"" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - afapa-network

  n8n:
    container_name: afapa-n8n
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      N8N_HOST: 0.0.0.0
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:-please-change-me}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - afapa-network

  waha:
    container_name: afapa-waha
    image: devlikeapro/waha
    restart: unless-stopped
    ports:
      - "3000:8000"
    env_file:
      - .env
    environment:
      WAHA_ENCRYPTION_KEY: ${WAHA_ENCRYPTION_KEY:-please-change-me}
      WAHA_API_KEY: ${WAHA_API_KEY:-please-change-me}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - afapa-network

  backend:
    container_name: afapa-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      db:
        condition: service_healthy
      n8n:
        condition: service_started
      waha:
        condition: service_started
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${PORT}/health || exit 1" ]
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - afapa-network

networks:
  afapa-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  n8n_data:
    driver: local
